# See https://docs.netlify.com/configure-builds/file-based-configuration/

[build.environment]
  NODE_VERSION = "22"

[context.production.environment]

  # We set NODE_ENV to development so that
  # Netlify will install devDependencies in package.json.
  NODE_ENV = "development"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"
