# Set site.output == "app"
output: "app"

# Set site.image-set == "images/app"
image-set: "images/app"

# Only the `app` collection should render.
# See _config.yml for notes on collections.
collections:
  app:
    output: true

# Remove baseurl
baseurl: ""

# Exclude from this build
exclude:
  # Build tools
  - run.js
  - Gemfile
  - Gemfile.lock
  - README*
  - LICENSE*
  - CHANGELOG*
  - node_modules
  - eslint.json
  - gulpfile.js
  - package.json
  - package-lock.json
  - CNAME
  - .sass-cache

  # Watched & compiled by Webpack, no need for Jekyll to process.
  # Jekyll only needs to watch /assets/js/dist
  - /assets/js/main.js
  - /assets/js/_src

  # Collections that must not be processed
  # for this output format
  - _docs
  - _api
  - _epub

  # Things we don't need for an app
  - deploy.sh
  - fr
  - netlify.toml
  - robots.txt
  - sitemap.xml
  - test.sh
  - assets/profiles
  - /*/package.opf
  - /*/toc.ncx
  - /*/images/print-pdf
  - /*/images/screen-pdf
  - /*/images/web
  - /*/images/epub
  - /*/styles/print-pdf*
  - /*/styles/screen-pdf*
  - /*/styles/web*
  - /*/styles/epub*
