# Set site.output == "epub"
output: "epub"

# Set site.image-set == "images/epub"
image-set: "images/epub"

# Only the `epub` collection should render.
# See _config.yml for notes on collections.
collections:
  epub:
    output: true

exclude:
  # The usual excludes from _config.yml
  - run.js
  - Gemfile
  - Gemfile.lock
  - README*
  - LICENSE*
  - CHANGELOG*
  - node_modules
  - eslint.json
  - gulpfile.js
  - package.json
  - package-lock.json
  - CNAME

  # Watched & compiled by Webpack, no need for Jekyll to process.
  # Jekyll only needs to watch /assets/js/dist
  - /assets/js/main.js
  - /assets/js/search.js
  - /assets/js/_src

  # Collections that must not be processed
  # for this output format
  - _api
  - _app
  - _docs

  # Exclude files we don't need for epub
  - deploy.sh
  - fr
  - netlify.toml
  - robots.txt
  - sitemap.xml
  - test.sh
  - /assets/fonts
  - /*/styles/print-pdf.scss
  - /*/styles/screen-pdf.scss
  - /*/styles/web.scss
  - /*/styles/app.scss
  - /*/styles/*.dic
  - /*/index.md
  - /*/images/print-pdf
  - /*/images/screen-pdf
  - /*/images/web
  - /*/images/app

  # Temporarily exclude book files for faster builds
  # - assets
  # - book
  # - samples

# We deliberately empty the keep_files list here,
# so that files we don't want don't end up in the epub
# but not in the manifest.
keep_files:
  # - assets
  # - book
  # - samples

# Map file extensions to media types for the opf
media-types:
  html: "application/xhtml+xml"
  xhtml: "application/xhtml+xml"
  css: "text/css"
  jpg: "image/jpeg"
  jpeg: "image/jpeg"
  gif: "image/gif"
  png: "image/png"
  svg: "image/svg+xml"
  ttf: "application/font-sfnt"
  otf: "application/font-sfnt"
  woff: "application/font-woff"
  woff2: "font/woff2"
  mp3: "audio/mpeg"
  mp4: "audio/mp4"
  ncx: "application/x-dtbncx+xml"
  txt: "text/plain"
  js: "application/javascript"
  unknown: "application/octet-stream"
