# Live website build config
# Use this to override defaults in _config.yml

# This is the live build
build: live

# URLs
canonical-url: "https://example.com"
baseurl: "/example"

# Only the `api` collection should render by default.
# See _config.yml for notes on collections.
# To turn off all collections, including _api,
# you must include a `collections:` node that will
# override the default in _config.yml. You can use:
# collections:
#   docs:
#     output: false
collections:
  api:
    output: true

# Exclude list
exclude:
  # Build tools
  - README.md
  - LICENSE
  - run.js
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - node_modules
  - gulpfile.js
  - eslint.json
  - CHANGELOG.md
  - /*/images/source

  # Watched & compiled by Webpack, no need for Jekyll to process.
  # Jekyll only needs to watch /assets/js/dist
  - /assets/js/main.js
  - /assets/js/search.js
  - /assets/js/_src

  # Collections that must not be processed
  - _app
  - _docs
  - _epub

  # Colour profiles for conversions
  - /assets/profiles

  # Scripts we don't need for web output
  - /assets/js/heading-titles.js

  # Book files we don't need for web
  - /*/images/print-pdf
  - /*/images/screen-pdf
  - /*/images/epub
  - /*/images/app
  - /*/styles/epub*
  - /*/styles/print-pdf*
  - /*/styles/screen-pdf*
  - /*/styles/app*
  - /*/package.opf
  - /*/toc.ncx

  # Exclude web images only if you keep_files them below
  # - /*/images/web

  # Exclude translations not ready for prime time
  # - /*/fr

# Keep list. Adjust for faster output,
# if you know what you're doing.
keep_files:
  # - book/images/print-pdf
  # - book/images/screen-pdf
  # - book/images/web
  # - book/images/epub
  # - book/fonts
  # - book/styles
  # - book/01.html
  # - book/02.html
